FROM python:3.11-slim

WORKDIR /var/task

RUN pip install --no-cache-dir --upgrade pip

COPY requirements.txt /var/task/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt awslambdaric
COPY app /var/task/app
COPY handler.py /var/task/handler.py

ENTRYPOINT ["python", "-m", "awslambdaric"]
CMD ["handler.handler"]
